wandb:
  run_name: "meta-llama/Meta-Llama-3.1-8B-Instruct" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
num_gpus: 1
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "meta-llama/Meta-Llama-3.1-8B-Instruct" #if you use openai api, put the name of model
  chat_template: "meta-llama/Meta-Llama-3.1-8B-Instruct"
  size_category: "<10B"
  #size: 70553706496
  release_date: "7/24/2024"