wandb:
  run_name: "meta-llama/Meta-Llama-3.1-405B-Instruct-FP8" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
num_gpus: 8
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "meta-llama/Meta-Llama-3.1-405B-Instruct-FP8" #if you use openai api, put the name of model
  chat_template: "meta-llama/Meta-Llama-3.1-405B-Instruct-FP8"
  size_category: "30B≤"
  size: 410000000000
  release_date: "7/24/2024"